repos:
  - repo: https://github.com/Quantco/pre-commit-mirrors-black
    rev: 24.4.2
    hooks:
      - id: black-conda
        args:
          - --safe
          - --target-version=py311
  - repo: https://github.com/Quantco/pre-commit-mirrors-flake8
    rev: 7.0.0
    hooks:
      - id: flake8-conda
  - repo: https://github.com/Quantco/pre-commit-mirrors-isort
    rev: 5.13.2
    hooks:
      - id: isort-conda
        additional_dependencies: [-c, conda-forge, toml=0.10.2]

