name: monitor
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11.*
  - pytest
  - pandas
  - pyyaml
  - numpy
  - matplotlib
  - pre-commit
  - google-auth
  - pip
  - pydantic>2.0
  - git_root
  - google-api-python-client==2.48.0
  - python-telegram-bot==13.11
  - orgparse
