name: monitor
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11.*
  - pytest
  - pandas
  - pyyaml
  - numpy
  - matplotlib
  - pre-commit
  - google-auth
  - pip
  - pydantic>=2.0
  - git_root
  - google-api-python-client
  - python-telegram-bot>=20.0
  - orgparse
